model: yolov8m.pt
imgsz: 1536
epochs: 200
batch: 4
workers: 4
device: "0"
seed: 42
patience: 60
project: runs
name: defect_yolov8m_1536_detect_all
conf_threshold: 0.25
iou_threshold: 0.5
save_period: 10
amp: true
cache: false
augment:
  degrees: 4.0
  translate: 0.05
  scale: 0.15
  shear: 0.0
  perspective: 0.0
  fliplr: 0.5
  flipud: 0.0
  mosaic: 0.10
  mixup: 0.0
  close_mosaic: 15
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.08
